### ISSUE TITLE
Stereo speakers

### ISSUE THREAD

**Issue by wallenium** [TheNitek/RfidShelf#11]
Hi There,
thanks a lot for your project. That exactly what i am searching for. 

Is there any issue in using two speakers for stereo? or how is it handled? is it possible?

**Comment by TheNitek** [comment]
Shouldn't be an issue. The firmware tries (only works if the VS1053 patch is available on the SD Card) to downmix the audio to mono, but it should play on both channels.

**Comment by TheNitek** [comment]
Oh and of course you have to build a hardware variant that is capable of stereo playback (e.g. the adafruit board)

**Comment by wallenium** [comment]
As far as I know,t he VS1053 VS1053B MP3 Module is capable of returning stereo?

Ordered the ShelfBoard, this one needs to be modified for sure. maybe sound of mono is good enough, not sure. What do you use currently? Could cancel most components and use adafruit, works as well.

another question: posible to use an external sd card slot to be able to add it to the shelf itsself?

**Comment by TheNitek** [comment]
Yes, the MP3 module is able to play stereo, but I try to enable the mono downmix so no audio is lost when using one speaker only.

The ShelfBoard is designed for a mono amplifier, so while it might be possible to connect a stereo one (I did this in the earlier stages of development) it is not ideal. The adafruit board has the stereo amp integrated, so while not being the cheapest solution, it is most probably the most easy one.
If you want to keep it cheap you can try something like this in combination (note: there might be cheaper version of this around, just looked for the first one I could find): https://www.aliexpress.com/item/1pcs-3-5MM-3Pole-Gold-plated-Plug-Free-Welding-Dual-Channel-Audio-Headphone-Plug-Stereo-Adapter/32833822485.html and https://www.aliexpress.com/item/Mini-PAM8403-3W-two-2-Channel-Way-Double-Track-Power-Audio-Amplifier-Module-Volume-Adjustment-Stereo/32857928954.html

Any SPI SD card reader should work (on the board it is actually also a sd slot separated from the mp3 decoder part, the just happen to be on the same board by "coincidence"), but you probably don't need it since you can manage the files via the web interface.

**Comment by wallenium** [comment]
adafruit: most easy or best sound?

I guess the adafruit should have a better quality than the VS1053 VS1053B.. at least the specs are better ;) I ordered one. Adafruit is stable..

Web interface sounds nice.

One last question: easy solution for a button-based (+ and -) volume control?

**Comment by TheNitek** [comment]
Well to be honest: This is not a hifi solution, so I would not get my hope to high regarding sound quality. This works perfectly for kids room but of course it cannot compete with a professionel hifi solution.

Volume control is currently not possible and something that I planned for the webinterface. There are no more GPIOs available for hardware controls (if I remember correctly there is still an analog port available which might work, bit I am not sure right now)

**Comment by wallenium** [comment]
yes, i know. will test the mono version first. Quality should be good enough. Should be for my kids room, will work. The old device we currently use is bad quality of sound, should be better.

Thanks a lot for your effort and support. I'll test if analog port is working once i receive the last parts...  if you have a further idea, would be great to share.

**Comment by wallenium** [comment]
Just one question: Have you worked with IO extenders such as https://de.aliexpress.com/item/MCP23017-Serial-Interface-Module-IIC-I2C-SPI-MCP23S17-Bidirectional-16-Bit-I-O-Expander-Pins-10Mhz

Maybe this would work to extend the GPIO and add possibilities for hardware buttons (volume, next/previous track). Analog potentiometer would be an option for volume, but not the best solution...

**Comment by BeAr1987** [comment]
I made a fork with a poti for volume control a few versions ago, you can find my code here: https://github.com/BeAr1987/RfidShelf

**Comment by TheNitek** [comment]
I didn't go for IO expanders, because I wanted to keep this project as cheap and easy to use as possible. Nevertheless it should be possible to add one (I guess you could even add the poti directly to the speaker wires without any software integration at all - but I'm not 100% sure).

Looking at the options today, I'd probably start the project with an ESP32 now which should offer enough GPIOs of the shelf (and a few other nice bonus features).
