### ISSUE TITLE
Can't connect & flash once everything is assembled

### ISSUE THREAD

**Issue by leachiM2k** [TheNitek/RfidShelf#27]
Hello,
thank you a lot for this project. It's pretty cool. I'm already using a phoniebox, but want to have a more stable and speedier solution. But...
I've soldered every part to one system with wires (no jumper cables) and have now the issue that I can't connect to NodeMCU by USB anymore. Is it possible that wiring there is an issue with a connection if some of the ports are used by other hardware? I've read something about a special role of GPIO 0 (D3)...
Do you know something about it? Or did you have similar issues?

**Comment by TheNitek** [comment]
Glad you like my project :-)
I had trouble from time to time to get the ESP to flash, but not in general. I the serial terminal still working? If not my guess would be incorrect wiring, because that should always work.
If it does, you can try to manually enter flash mode using the buttons on the ESP.

Did you change the PIN compared to my design? Is the shelf firmware already on? Because I noticed that a delay at the beginning of setup() helps to improve the reliability of flashing, so it's part of the firmware.

**Comment by leachiM2k** [comment]
Ok, I took my time and checked everything again and again. I tried it with a different ESP8266 and had the same issue. 🤔 
In the end I had two power-only USB cables that provide no data connection. 

Now everything is working, but somehow laggy... Every time I open the webpage the player stops working for a second.

I have two questions:
- Is it true, that you can not upload mp3 files through web interface?
- Why did you wire A- of the amplifier to GND on board instead of the audio jack on VS1053 like you did with A+?

**Comment by TheNitek** [comment]
The web interface interferes with the mp3 playback. I don't think there is an easy way to avoid that, but I don't consider it a problem, since I use the web for admin propuses only. You can use it to upload MP3s. Works quite well, but the WiFi performance makes it somewhat annoying when uploading bigger files.

Since I didn't get differential output to work, the AMP only needs GND and one of the audio signals. GND from the VS1053 wouldn't be any different.
